"""drift_check

Revision ID: drift000
Revises: cf58df5daa7d
Create Date: 2026-03-14 16:46:46.013586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'drift000'
down_revision: Union[str, Sequence[str], None] = 'cf58df5daa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ec2_instance_arn'), 'ec2_instance', ['arn'], unique=True)
    op.create_index(op.f('ix_ec2_instance_owner_id'), 'ec2_instance', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ec2_instance_region'), 'ec2_instance', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ec2_instance_region'), table_name='ec2_instance')
    op.drop_index(op.f('ix_ec2_instance_owner_id'), table_name='ec2_instance')
    op.drop_index(op.f('ix_ec2_instance_arn'), table_name='ec2_instance')
    # ### end Alembic commands ###
