"""baseline

Revision ID: e1d23dfc935e
Revises: 
Create Date: 2026-03-13 12:03:51.427232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d23dfc935e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ec2_instance',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('arn', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('architecture', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('tenancy', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('scan_run',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('id_filter', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('region_filter', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('observation_window', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', 'in_progress', name='findingstatus'), nullable=False),
    sa.Column('started_on', sa.DateTime(), nullable=True),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.Column('scanned_count', sa.Integer(), nullable=True),
    sa.Column('initiated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('utilization_metric',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('missing_data', sa.Float(), nullable=True),
    sa.Column('cpu_avg', sa.Float(), nullable=True),
    sa.Column('cpu_max', sa.Float(), nullable=True),
    sa.Column('cpu_p95', sa.Float(), nullable=True),
    sa.Column('cpu_p99', sa.Float(), nullable=True),
    sa.Column('power_avg', sa.Float(), nullable=True),
    sa.Column('power_max', sa.Float(), nullable=True),
    sa.Column('power_p95', sa.Float(), nullable=True),
    sa.Column('power_p99', sa.Float(), nullable=True),
    sa.Column('memory_avg', sa.Float(), nullable=True),
    sa.Column('memory_max', sa.Float(), nullable=True),
    sa.Column('memory_p95', sa.Float(), nullable=True),
    sa.Column('memory_p99', sa.Float(), nullable=True),
    sa.Column('network_avg', sa.Float(), nullable=True),
    sa.Column('network_max', sa.Float(), nullable=True),
    sa.Column('network_p95', sa.Float(), nullable=True),
    sa.Column('network_p99', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['ec2_instance.resource_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scan_run.run_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('finding',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('utilization_metric_id', sa.Integer(), nullable=False),
    sa.Column('assessment', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', 'in_progress', name='findingstatus'), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.Column('constraints', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['ec2_instance.resource_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scan_run.run_id'], ),
    sa.ForeignKeyConstraint(['utilization_metric_id'], ['utilization_metric.metric_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_table('recommendation',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('recommended_config', sa.String(), nullable=False),
    sa.Column('optimization_category', sa.String(), nullable=False),
    sa.Column('monthly_cost_impact', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.finding_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('finding')
    op.drop_table('utilization_metric')
    op.drop_table('scan_run')
    op.drop_table('ec2_instance')
    # ### end Alembic commands ###
